version: '2'

services:
  app:
    build: .
    image: senguoph
    container_name: senguoph_backend
    stdin_open: true
    tty: true
    ports:
      - "8989:8989"
    volumes:
      - .:/home/senguoph/backend
    working_dir: /home/senguoph/backend
    environment:
      MYSQL_USER:
      MYSQL_PASSWORD:
    depends_on:
      - mysql
      - redis
    command: ["wait-for.sh", "mysql:3306", "--", "python3", "app.py"]
    networks:
      - backend

  mysql:
    image: mysql:5.6
    container_name: senguoph_mysql
    ports:
      - "3310:3306"
    volumes:
      - ./docker/data/mysql:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD:
    networks:
      - backend

  redis:
    image: redis:4.0-alpine
    container_name: senguoph_redis
    ports:
      - "6388:6379"
    volumes:
      - ./docker/data/redis:/data:rw
    networks:
      - backend

networks:
  backend:
